angular.module('SED.studentProfile', [])
.controller('studentCtrl', function($scope, $state, Auth, Centers, Students) {

 $scope.data={};
  Centers.getAllCenters()
  .then(function(centers){
    $scope.data.centers=centers;
  });
  Students.getCurrentStudent()
  .then(function(resp){
    $scope.data.student=resp;
  });
  $scope.viewTeachers=function(){
  	Students.viewTeachers()
  	.then(function(resp){
  		$scope.data.teachers=resp;
  		console.log(resp);
  	});
  }
   $scope.viewGames=function(){
    Students.viewGames()
  	.then(function(resp){
  		$scope.data.teachers=resp;
  		console.log(resp);
  	});
  }
  $scope.viewRecords=function(){
  	Students.viewRecords()
  	 .then(function(resp){
  	 	$scope.data.records=resp;
  	 	console.log(resp);
  	 });
  }
  $scope.editProfile=function(){
  	Students.editProfile()
  	.then(function(resp){
  		$scope.data.info=resp;
  	});
  }
 });